### ISSUE TITLE
Question on functionnality

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach-chatbot#1]
Question: I can send a report link for the recent earthquake in that region even though we didn’t create an event for it?

**Comment by matthewberryman** [comment]
At the moment I have manually entered one in for the Iraq/Iran earthquake. I propose adding ones in automatically per https://github.com/MSFREACH/msf-reach-chatbot/issues/6
If we go down the path of creating events from non-event-linked report forms then we can develop a generic report key phrase list and response for that, in #5

**Comment by LucieGueuning** [comment]
Should open an issue for 'generic reports' and get the chatbot taking the key phrase list and response for that?

**Comment by matthewberryman** [comment]
If we do that it comes under exisiting issue https://github.com/MSFREACH/msf-reach-chatbot/issues/5
