### ISSUE TITLE
list of fields to search on

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach-chatbot#2]
- name
- areas (country/province/location)
- type of emergency
- date 
- description

**Comment by matthewberryman** [comment]
Which date/date(s) do you want to search on? There are multiple date fields as you've previously requested.

**Comment by matthewberryman** [comment]
Done bar dates (awaiting feedback)

**Comment by LucieGueuning** [comment]
dates of disaster

**Comment by matthewberryman** [comment]
Thanks was just making sure you didn't also want the ones tracking when event was opened etc. I will add dates of disaster in on Monday.
