### ISSUE TITLE
Need more precis detection of keyword used by end-user

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach-chatbot#3]
## Expected Behavior
understand my keywords or ask for synonym (at least)

## Actual Behavior
ask for repetition

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:Windows 8 Professional - 64bit
  - Platform:REACH
![capture2](https://user-images.githubusercontent.com/25951555/33362308-d72a6ce4-d516-11e7-972b-208d3eb3f99a.PNG)

**Comment by matthewberryman** [comment]
the chatbot only understands what it's been told about, which will come from:
Core language (let's work on that here https://github.com/MSFREACH/msf-reach-chatbot/issues/5 )
as well as automatic population of responses from events as they are added to reach https://github.com/MSFREACH/msf-reach-chatbot/issues/6
